version: 2.1

orbs:
  macos: circleci/macos@2.3.4

jobs:
  mac-os:
    parameters:
      version:
        default: "14.0.1"
        type: string
    macos:
      xcode: << parameters.version >>
    resource_class: macos.x86.medium.gen2
    steps:
      - macos/switch-ruby:
          version: "3.1.3"
      - run: gem --version && ruby --version && cat /Users/distiller/.rbenv/.ruby-version
workflows:
  workflow-mac:
    jobs:
      - mac-os:
          matrix:
            parameters:
              version: ["14.0.1", "14.2.0"]
